# Site settings
title:          HU Qian
description:    "HU Qian's Academic Blog!"
baseurl:        "/ProfileHQ" #大小写敏感
url:            "https://froggycroak.github.io"
future: true


# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         HU Qian
  url:          https://froggycroak.github.io/profilehq/
  email:        huqian.archi@outlook.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  # - jemoji #Uncomment this to allow emoji in your post

# theme:      tale
# remote_theme: chesterhow/tale

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       3

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale

# 
collections:
  projects:
    output: true
    permalink: /projects/:name
  publications:
    output: true
    permalink: /publications/:name
  postdesign:
    output: true
    permalink: /design/:title
  postresearch:
    output: true
    permalink: /research/:title

# seo:
#   title_separator: " | "
#   title: "{{ page.abbrev | default: page.title | default: site.title }}{{ site.title_separator }}{{ site.title }}"

